### ISSUE TITLE
Not Compatible with WFRP and Chat Autoloader

### ISSUE THREAD

**Issue by ppepin34** [crash1115/ready-check#4]
The module doesn't seem to be compatible with the WFRP system. It doesn't properly render the button. 
![image](https://user-images.githubusercontent.com/59454905/103156935-f44a6d80-477b-11eb-9f61-cb4babb75b2e.png)
It doesn't render at all for the player.

It doesn't render when Polyglot is enabled as well, and seems to break Polyglot totally. Even with Ready, Set, Go! disabled, Polyglot ceases to function.

**Comment by crash1115** [comment]
Hey thanks for the report and your interest in the module. When you say it "breaks" Polyglot, what exactly does that mean? Do you get any errors in the console?

**Comment by ppepin34** [comment]
At first it was completely unresponsive. I ended up making a new world to try again, and it seems to be either Polyglot is active, or Ready, Set Go! I made the mistake of deleting my old world since I couldn't get Polyglot going and that is more important to this game.

**Comment by crash1115** [comment]
Understood. Last question - what versions of Foundry, wfrp, and Polyglot are you currently running, and what other modules (if any) are you using? Just wanna make sure I'm getting the whole picture here so I can diagnose effectively.

In the meantime, I'll take a look into these and keep you updated. System compatibility is going to be the first thing I try to fix since that's more broadly applicable, but for the time being I've added a warning to the readme to alert folks about the incompatibilities with both system and module.

**Comment by crash1115** [comment]
Quick updates:
- I could not reproduce the issue where the RSG! button didn't display for players.
- I could not reproduce any conflicts with RSG! and Polyglot. It seems to work fine running the latest versions of everything.
- I could fix the display issue in your screenshot. That fix will go out in the next patch.

It looks like Polyglot has been having some issues with wfrp in the recent past, but none of the testing I did indicated that there's any conflicts with RSG!. Nothing in the code overlaps or interferes, so my best guess is that there might be some other module causing issues, or that something is out of date.

**Comment by ppepin34** [comment]
It's still not functioning for me. I'm going to make a test world and add modules one by one to see where the conflict is because *stares at list* I have a lot

**Comment by ppepin34** [comment]
I went through each module one by one and it didn't replicate. It has to be some combination of what I previously did. I'll see if I can get a console error for you

**Comment by ppepin34** [comment]
The only errors I'm getting are from Show Drag Distance and Polyglot. It begins to load the button, then unloads. I tried without Polyglot and it did the same. And I just found it. It's Chat Autoloader. When I have messages in the the chat log, it gets rid of the indicator. It doesn't if the chat log is empty.

**Comment by crash1115** [comment]
Ah, yeah that one makes more sense. I did some research and I think the functionality that Chat Autoloader provides is now part of core, since the module itself seems to have been deprecated. You should be all set without it, but I'll take a look and see if there's something I can do with the button rendering to prevent the conflict at all.

Thanks for taking the time to dig into it, it's greatly appreciated!

**Comment by ppepin34** [comment]
No problem! I'm glad I could help. Fortunately Moo Man drastically reduced the chat log size so it shouldn't take too long to load. Now it's just all of the official modules, lol.

**Comment by crash1115** [comment]
Lol I feel that. Double-edged sword sometimes - so many awesome modules, so little time!

I'll have a fix pushed for both of these issues super shortly. Lemme know if it fixes everything for ya.
